# Use an official Node.js runtime as a parent image
FROM node:23-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY verify-frontend/package*.json .

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY verify-frontend/ .

EXPOSE 3000

# Start Nginx
CMD ["npm", "start"]